let places = [
    {
    name: 'NextGen Advisors',
    industry: 'Professional Services',
    contact: 'John Rutton',
    city: 'Newark',
    state: 'NJ',
    sales: 535000,
    },
    {
    name: 'Receivers Inc',
    industry: 'Legal',
    contact: 'Stacey Martin',
    city: 'New York',
    state: 'NY',
    sales: 201000,
    },
    {
    name: 'Ethan Allen',
    industry: 'Textile',
    contact: 'Mark Shamburger',
    city: 'Seacaucus',
    state: 'NJ',
    sales: 735000,
    },
    {
    name: 'Russian River',
    industry: 'Transportation',
    contact: 'Phil Butterworth',
    city: 'Parsipanny',
    state: 'NJ',
    sales: 205000,
    },
    {
    name: 'Johnson',
    industry: 'Legal',
    contact: 'Beverly Stephens',
    city: 'Syracuse',
    state: 'NY',
    sales: 135000,
    },
    {
    name: 'Kravet',
    industry: 'Textile',
    contact: 'Jan Farnsworth',
    city: 'Ithaca',
    state: 'NY',
    sales: 105000,
    },
    {
    name: 'Wacomb',
    industry: 'Professional Services',
    contact: 'Larry Peters',
    city: 'Elizabeth',
    state: 'NJ',
    sales: 130000,
    },
    {
    name: 'Farnsworth',
    industry: 'Transportation',
    contact: 'Peter Dalton',
    city: 'Philadelphia',
    state: 'PA',
    sales: 437000,
    },
    {
    name: 'Barnes',
    industry: 'Legal',
    contact: 'John Percy',
    city: 'White Plains',
    state: 'NY',
    sales: 350000,
    },
]

module.exports = places